import { process } from '../../sys/process.ts'
// A WeGene-style narrative PDF is not a raw genotype file. Mirobody's genetic handler only accepts
// the text export whose first line is "# This data file generated by WeGene at". This module reads
// a short list of key variants off the narrative (locally, never the whole 2924-page text to a model)
// and stores them with the caveats that go with a consumer report.

import { spawnSync } from '../../sys/child_process.ts'
import { existsSync } from '../../sys/fs.ts'
import { userInfo } from '../../sys/os.ts'
import { join } from '../../sys/path.ts'
import type { Provenance } from '../contracts/common.ts'
import { memoryFor } from '../core/memory.ts'
import { readJson, writeJsonAtomic } from '../core/store.ts'

export const RAW_MARKER = '# This data file generated by WeGene at'

export const RAW_EXPORT_ZH = '请在微基因 App 中导出「原始数据」文本，勿使用叙述版 PDF。将该 txt 文件发送到健康对话中，才能按位点保存。叙述版仅在这台电脑上摘录少数关键位点。'

export const GENETICS_CAVEATS = [
  '这是消费级基因检测的叙述报告，不是临床诊断，也不能据此判断患病或健康。',
  '报告注明仅展示部分位点。未列出的位点，不代表不存在。',
  '与用药相关的位点仅供提醒：开始、停止或更换药物，请咨询开药的医生；LongPi 不提供剂量。',
  '基因型仅保存在这台电脑上，不用于研究共享。',
]

/** Variants worth keeping from a narrative report. Anything else stays in the PDF. */
const KEY_RSIDS = [
  'rs429358', 'rs7412', 'rs1801133', 'rs1801131', 'rs1801394', 'rs1229984', 'rs671',
  'rs4988235', 'rs182549', 'rs762551', 'rs4149056', 'rs2231142', 'rs9923231', 'rs11212617', 'rs2802288',
] as const

const RSID_NOTE: Record<string, string> = {
  rs429358: 'APOE',
  rs7412: 'APOE',
  rs1801133: 'MTHFR 叶酸',
  rs1801131: 'MTHFR 叶酸',
  rs1801394: 'MTRR 叶酸',
  rs1229984: 'ADH1B 酒精',
  rs671: 'ALDH2 酒精',
  rs4988235: 'MCM6 乳糖',
  rs182549: 'MCM6 乳糖',
  rs762551: 'CYP1A2 咖啡因',
  rs4149056: 'SLCO1B1 他汀',
  rs2231142: 'ABCG2',
  rs9923231: 'VKORC1 华法林',
  rs11212617: '二甲双胍相关',
  rs2802288: 'FOXO3',
}

export interface GeneticVariant {
  rsid: string
  genotype: string
  note_zh: string
}

export interface GeneticsSummary {
  version: 1
  vendor: 'wegene' | 'unknown'
  /** Local only. Not copied into memory, so it is not sent to the model. */
  sample_id: string
  generated: string
  variants: GeneticVariant[]
  headlines_zh: string[]
  caveats_zh: string[]
  raw_export_zh: string
  stored_at: string
  source: 'pdf' | 'text' | 'raw'
  /** How many PDF pages were opened. 0 when the input was already text. */
  pages_read: number
}

function emptySummary(source: GeneticsSummary['source']): GeneticsSummary {
  return {
    version: 1, vendor: 'unknown', sample_id: '', generated: '', variants: [], headlines_zh: [],
    caveats_zh: [...GENETICS_CAVEATS], raw_export_zh: RAW_EXPORT_ZH, stored_at: '', source, pages_read: 0,
  }
}

export function isWeGeneRaw(text: string): boolean {
  return text.slice(0, 400).includes(RAW_MARKER)
}

export function isWeGeneNarrative(text: string): boolean {
  return /微基因|WeGene/i.test(text.slice(0, 4000)) && /基因检测|rs\d{4,}|祖源/.test(text.slice(0, 8000))
}

function genotypeNear(text: string, rsid: string): string {
  const re = new RegExp(rsid, 'ig')
  let match: RegExpExecArray | null
  while ((match = re.exec(text))) {
    const after = text.slice(match.index + rsid.length, match.index + rsid.length + 80)
    // WeGene tables put the genotype on its own line under the rsid (RS429358 / APOE / TT).
    const lines = after.split('\n').map((line) => line.trim()).filter(Boolean).slice(0, 4)
    const lined = lines.find((line) => /^[ACGT]{2}$/i.test(line))
    if (lined) return lined.toUpperCase()
    const slash = /([ACGT])\s*[/／]\s*([ACGT])/i.exec(after)
    if (slash && (slash.index ?? 99) < 16) return `${slash[1]}${slash[2]}`.toUpperCase()
    const glued = /^\s*([ACGT]{2})(?:[^A-Za-z]|$)/i.exec(after)
    if (glued?.[1]) return glued[1].toUpperCase()
  }
  return ''
}

function apoePhrase(variants: GeneticVariant[]): string {
  const a = variants.find((row) => row.rsid === 'rs429358')?.genotype
  const b = variants.find((row) => row.rsid === 'rs7412')?.genotype
  if (!a || !b) return ''
  const key = `${a}/${b}`
  const table: Record<string, string> = {
    'TT/CT': 'ε2/ε3', 'TT/TT': 'ε2/ε2', 'TT/CC': 'ε3/ε3', 'CT/CC': 'ε3/ε4', 'CC/CC': 'ε4/ε4',
  }
  const call = table[key]
  return call ? `APOE 常见对应 ${call}（rs429358 ${a}，rs7412 ${b}），不是诊断` : ''
}

/** Pull key variants out of narrative text. No personal name is kept. */
export function extractGeneticsText(text: string, source: GeneticsSummary['source'] = 'text'): GeneticsSummary {
  const summary = emptySummary(source)
  if (isWeGeneRaw(text)) {
    summary.vendor = 'wegene'
    summary.source = 'raw'
    summary.headlines_zh = ['这是微基因原始数据导出文件，可上传至健康数据服务保存位点，无需再上传叙述版 PDF。']
    return summary
  }
  if (/微基因|WeGene/i.test(text)) summary.vendor = 'wegene'
  const sample = /样本编号\s*[:：]\s*(\d{6,})/.exec(text)
  if (sample?.[1]) summary.sample_id = sample[1]
  const generated = /报告生成\s*[:：]\s*(20\d{2}-\d{2}-\d{2})/.exec(text)
  if (generated?.[1]) summary.generated = generated[1]
  const lower = text.toLowerCase()
  for (const rsid of KEY_RSIDS) {
    // WeGene tables print RS429358; the prose uses rs429358.
    if (!lower.includes(rsid)) continue
    const genotype = genotypeNear(text, rsid)
    if (!genotype) continue
    summary.variants.push({ rsid, genotype, note_zh: RSID_NOTE[rsid] ?? '' })
  }
  const star = /CYP2C19\s*\*\s*(\d)\s*[/／]\s*\*\s*(\d)/i.exec(text)
  if (star) summary.headlines_zh.push(`CYP2C19 *${star[1]}/*${star[2]}（据叙述报告；是否换药请咨询医生）`)
  const apoe = apoePhrase(summary.variants)
  if (apoe) summary.headlines_zh.unshift(apoe)
  const hapY = /父系单倍群[\s\S]{0,80}?([A-Z][0-9][A-Za-z0-9]{2,})/.exec(text)
  if (hapY?.[1] && hapY[1].length <= 24) summary.headlines_zh.push(`父系单倍群 ${hapY[1]}`)
  const hapM = /母系单倍群[\s\S]{0,40}?([A-Z][0-9][A-Za-z0-9]{1,})/.exec(text)
  if (hapM?.[1] && hapM[1].length <= 12) summary.headlines_zh.push(`母系单倍群 ${hapM[1]}`)
  return summary
}

function summaryPath(dataDir: string): string {
  return join(dataDir, 'datain', 'genetics.json')
}

export function readGenetics(dataDir: string): GeneticsSummary | null {
  const row = readJson<GeneticsSummary | null>(summaryPath(dataDir), (raw) => {
    if (!raw || typeof raw !== 'object') return null
    const value = raw as Partial<GeneticsSummary>
    if (!Array.isArray(value.variants)) return null
    return value as GeneticsSummary
  }, () => null)
  return row
}

/** Memory text has the variants and the caveats, never the sample id or a name. */
export function geneticsMemoryText(summary: GeneticsSummary): string {
  const bits = summary.variants.slice(0, 8).map((row) => `${row.note_zh ? `${row.note_zh} ` : ''}${row.rsid} ${row.genotype}`)
  const head = summary.headlines_zh[0] ?? ''
  const body = [head, bits.join('；')].filter(Boolean).join('。')
  const lead = summary.vendor === 'wegene' ? '微基因消费级报告' : '基因报告'
  return `${lead}${summary.generated ? `（${summary.generated}）` : ''}：${body || '未提取到关键位点'}。${GENETICS_CAVEATS[0]} ${RAW_EXPORT_ZH}`.slice(0, 500)
}

export function storeGenetics(dataDir: string, summary: GeneticsSummary, now = new Date()): GeneticsSummary {
  const saved: GeneticsSummary = { ...summary, stored_at: now.toISOString(), caveats_zh: [...GENETICS_CAVEATS], raw_export_zh: RAW_EXPORT_ZH }
  writeJsonAtomic(summaryPath(dataDir), saved)
  const text = geneticsMemoryText(saved)
  const provenance: Provenance = { kind: summary.source === 'pdf' ? 'import' : 'import', at: saved.stored_at, by: 'M7' }
  try {
    memoryFor(dataDir).apply([{
      op: 'add',
      item: {
        kind: 'note',
        text_zh: text.slice(0, 200),
        confirmed: false,
        provenance,
      },
    }], 'M7')
  } catch {
    // the summary file is the record; memory is the digest
  }
  return saved
}

interface SectionDump { title: string; text: string }

/** Open only the TOC sections that match the key traits. The rest of a 2924-page PDF stays unread. */
export function extractGeneticsPdf(pdfPath: string): GeneticsSummary {
  const script = `
import json, sys
import fitz
path, raw = sys.argv[1], sys.argv[2]
want = json.loads(raw)
doc = fitz.open(path)
toc = doc.get_toc() or []
picked = []
seen_titles = set()
for word in want:
    for level, title, page in toc:
        if word in (title or "") and title not in seen_titles:
            picked.append((title, page))
            seen_titles.add(title)
            break
picked = picked[:18]
parts = []
seen = set()
for title, page in picked:
    for number in range(page, page + 4):
        if number < 1 or number > doc.page_count or number in seen:
            continue
        seen.add(number)
        text = doc[number - 1].get_text("text") or ""
        parts.append({"title": title, "text": text[:3500]})
cover = doc[0].get_text("text") if doc.page_count else ""
print(json.dumps({"cover": cover[:1500], "sections": parts, "pages_read": len(seen)}, ensure_ascii=False))
`
  const keywords = ['祖源成分', '父系单倍群', '母系单倍群', '叶酸', '酒精代谢', '乳糖', '阿尔茨海默', '载脂蛋白', 'APOE', '氯吡格雷', '华法林', '阿托伐他汀', '瑞舒伐他汀', '阿司匹林', '二甲双胍', '痛风', '咖啡因']
  // dsh runs each person with HOME pointed at that profile, which hides the
  // account's Python user site (where PyMuPDF lives). Read packages from the
  // login home; the persona home stays the default for everything else.
  const python = ['/usr/bin/python3', '/opt/homebrew/bin/python3'].find((bin) => existsSync(bin)) ?? 'python3'
  let loginHome = ''
  try { loginHome = userInfo().homedir } catch { loginHome = '' }
  const run = spawnSync(python, ['-c', script, pdfPath, JSON.stringify(keywords)], {
    encoding: 'utf8', timeout: 120_000, maxBuffer: 8_000_000,
    env: { ...process.env, ...(loginHome ? { HOME: loginHome } : {}) },
  })
  if (run.status !== 0 || !run.stdout.trim()) {
    const failed = emptySummary('pdf')
    failed.headlines_zh = ['未能从 PDF 中提取位点。请改用微基因原始数据导出文件。']
    return failed
  }
  let parsed: { cover?: string; sections?: SectionDump[]; pages_read?: number }
  try {
    parsed = JSON.parse(run.stdout) as typeof parsed
  } catch {
    return emptySummary('pdf')
  }
  // Drop the cover line that is "<name> 基因检测报告". The sample id stays; the name does not (D10).
  const text = `${parsed.cover ?? ''}\n${(parsed.sections ?? []).map((row) => `${row.title}\n${row.text}`).join('\n')}`
    .split('\n').filter((line) => !/基因检测报告/.test(line)).join('\n')
  const summary = extractGeneticsText(text, 'pdf')
  summary.pages_read = parsed.pages_read ?? 0
  if (summary.variants.length === 0 && summary.headlines_zh.length === 0) {
    summary.headlines_zh = ['叙述版目录页中未匹配到关键位点。如需按位点查询，请使用原始数据导出文件。']
  }
  return summary
}
