// Chat tools for getting a report, a medicine line, a condition, and the narrative findings into LongPi.
// record_medication_statement already exists (tools-tracking); this does not register it again.

import type { Context } from '../../sys/cordis.ts'
import { defineTool } from '../../sys/dsh-tools.ts'
import type { CoreDeps } from '../contracts/index.ts'
import { jsonOut } from '../core/tool-kit.ts'
import { asJson } from '../json.ts'
import { rememberCondition } from './conditions.ts'
import { leadImaging, listFindings } from './narrative.ts'
import { isStoreKind } from '../stores/index.ts'
import { ingestDocument } from './upload.ts'
import { reportReaderProfile } from '../agents/report_reader.ts'

export function registerDatainTools(ctx: Context, deps: CoreDeps): void {
  ctx.tools.register(defineTool({
    name: 'forward_report',
    description: 'Send a checkup PDF or photo the person attached (a filesystem path) to their Mirobody record, and read back what was extracted: indicator count, date, and narrative lines (TI-RADS, BI-RADS, 总检, 医师建议). A page that names someone else is not uploaded. A duplicate of a file already sent is not uploaded again. A WeGene narrative PDF is summarised on this computer and is not sent as a lab report; a WeGene raw text export (header "# This data file generated by WeGene at") is sent. Never include the person\'s name in what you say.',
    parameters: {
      path: { type: 'string', required: true, description: 'Absolute path of the file they attached.' },
      note: { type: 'string', description: 'Optional short note. Do not put their name here.' },
      type: { type: 'string', enum: ['methylation', 'taxa', 'proteins', 'conditions'], description: 'Set when the file is a methylation chip export, a microbiome table, a protein panel, or an ICD-10 list. Omit for a checkup. The rows are stored on this computer after a shape check. Do not paste the raw matrix into the reply.' },
      sample_date: { type: 'string', description: 'YYYY-MM-DD when the file itself has no date.' },
      site: { type: 'string', enum: ['gut', 'oral'], description: 'Gut or oral, when a taxa file does not say.' },
    },
    output: jsonOut,
    timeoutMs: 120000,
    isConcurrencySafe: () => false,
    async execute(args) {
      const path = typeof args.path === 'string' ? args.path.trim() : ''
      if (!path || path.includes('\0')) return asJson({ ok: false, error: '没有文件路径。请让对方把报告发到对话里。' })
      try {
        const type = isStoreKind(args.type) ? args.type : undefined
        const site = args.site === 'gut' || args.site === 'oral' ? args.site : undefined
        const sample = typeof args.sample_date === 'string' && /^\d{4}-\d{2}-\d{2}$/.test(args.sample_date) ? args.sample_date : undefined
        const result = await ingestDocument(deps, {
          filename: path.split('/').pop() || 'report',
          path,
          note: typeof args.note === 'string' ? args.note.slice(0, 80) : '',
          confirm: true,
          ...(type ? { type } : {}),
          ...(site ? { site } : {}),
          ...(sample ? { sample_date: sample } : {}),
        })
        const digest = reportReaderProfile.fallback(null as never, result)
        return asJson({ ...result, read_back_zh: digest.read_back_zh, how_to_read: 'Read read_back_zh to them. Do not add a diagnosis, a dose, or their name. A TI-RADS or BI-RADS grade is the report\'s own words: suggest they take it to a doctor, and do not decide on a biopsy or a medicine.' })
      } catch {
        return asJson({ ok: false, error: '读不到这个文件。请让对方重新发一次。' })
      }
    },
  }))

  ctx.tools.register(defineTool({
    name: 'read_narrative_findings',
    description: 'Narrative lines kept from checkup reports (ultrasound TI-RADS / BI-RADS, conclusions, 总检 advice) and a short genetics summary if one was stored. Read-only. Does not include the person\'s name. Use it when they ask what the report said besides the lab numbers.',
    parameters: {},
    output: jsonOut,
    timeoutMs: 10000,
    isConcurrencySafe: () => true,
    async execute() {
      const rows = listFindings(deps.dataDir())
      const lead = leadImaging(rows)
      return asJson({
        findings: rows.slice(-20).map(({ id, date, kind, text_zh, grade }) => ({ id, date, kind, text_zh, ...(grade ? { grade } : {}) })),
        lead_zh: lead?.text_zh ?? '',
        how_to_read: 'Quote text_zh. A grade is the report\'s grade, not your diagnosis. Do not invent a biopsy, a drug, or a dose.',
      })
    },
  }))

  ctx.tools.register(defineTool({
    name: 'record_condition',
    description: 'Remember a condition or diagnosis the person stated (我有脂肪肝, 医生说缺铁性贫血). Stored on this computer only: Mirobody\'s conditions route returns 405, so do not tell them it was written there. Pass their words. This does not confirm the diagnosis and does not start a treatment.',
    parameters: {
      name_zh: { type: 'string', required: true, description: 'The condition in their words (脂肪肝, 桥本).' },
      state: { type: 'string', enum: ['current', 'past', 'suspected', 'ruled_out'], description: 'Default current. past if they said 以前有. suspected if they are not sure. ruled_out if a doctor excluded it.' },
      since: { type: 'string', description: 'YYYY-MM-DD if they gave a start. Omit otherwise.' },
      quote: { type: 'string', description: 'Their own words from this message.' },
    },
    output: jsonOut,
    timeoutMs: 10000,
    isConcurrencySafe: () => false,
    async execute(args) {
      const name = typeof args.name_zh === 'string' ? args.name_zh : ''
      const state = args.state === 'past' || args.state === 'suspected' || args.state === 'ruled_out' ? args.state : 'current'
      const saved = rememberCondition(deps.dataDir(), {
        name_zh: name,
        state,
        since: typeof args.since === 'string' ? args.since : '',
        quote_zh: typeof args.quote === 'string' ? args.quote : name,
        via: 'chat',
      })
      if (!saved.ok) return asJson(saved)
      return asJson({ ok: true, read_back: saved.read_back, how_to_read: 'Read read_back back. Do not turn it into a treatment or a dose.' })
    },
  }))
}
